### ISSUE TITLE
できた

### ISSUE THREAD

**Issue by Ryota69** [auqlue/aks#1]
できーた

**Comment by konemura** [comment]
test

**Comment by Ryota69** [comment]
![auqlue3](https://cloud.githubusercontent.com/assets/13809934/9289218/1ea3f02a-43a3-11e5-8fae-62365ea6f389.png)

**Comment by Ryota69** [comment]
![cooltext131934045776624](https://cloud.githubusercontent.com/assets/13809934/9289220/2f776d32-43a3-11e5-817f-78170b3fcaad.png)
